service: TPL_SERVICE_NAME

provider:
  # general settings
  name: aws
  stage: dev
  region: TPL_REGION
  profile: default
  deploymentMethod: direct
  # global function settings (apply to each declared function)
  runtime: provided.al2
  memorySize: 1024
  timeout: 28 # in seconds (API Gateway has a timeout of 29 seconds)
  logRetentionInDays: forever
  layers:
    - ${bref:layer.php-TPL_PHP_VERSION-fpm}

plugins:
  - ./vendor/bref/bref

functions:
  api:
    handler: index.php
    description: 'Deployed with Bref TPL_BREF_VERSION for PHP TPL_PHP_VERSION_PRETTY'
    events:
      - httpApi: '*'

# Exclude files from deployment
package:
  patterns:
    - '!node_modules/**'
    - '!tests/**'
